apiVersion: v1
kind: ConfigMap
metadata:
  name: config-sistema
  namespace: default
data:
  # --- DADO 1: Vai virar um arquivo físico (index.html) ---
  index.html: |
    <!DOCTYPE html>
    <html>
    <body>
      <h1>Teste Hibrido</h1>
      <p>O HTML vem de um Volume.</p>
      <p>As variaveis de ambiente estao na memoria do processo.</p>
    </body>
    </html>

  # --- DADOS 2 e 3: Vão virar Variáveis de Ambiente ---
  NOME_AMBIENTE: "PRODUCAO"
  NIVEL_LOG: "DEBUG"
  BANCO_DADOS_URL: "jdbc:mysql://localhost:3306/db"