apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-com-secret
  namespace: default
  labels:
    app: app-secreto
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-secreto
  template:
    metadata:
      labels:
        app: app-secreto
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        
        # --- PARTE 1: INJETANDO COMO ENV VAR ---
        env:
          - name: DB_PASSWORD  # Nome da variável no Linux
            valueFrom:
              secretKeyRef:    # Note que aqui muda de configMapKeyRef para secretKeyRef
                name: meu-segredo-banco
                key: senha-db

        # --- PARTE 2: MONTANDO COMO ARQUIVO (VOLUME) ---
        volumeMounts:
        - name: vol-chaves
          mountPath: /etc/segredos-app
          readOnly: true # Boa prática: Secrets devem ser somente leitura
        
        # Recursos (Mantendo seu padrão)
        resources:
          requests:
            cpu: "100m"
            memory: "64Mi"
          limits:
            cpu: "500m"
            memory: "128Mi"

      volumes:
      - name: vol-chaves
        secret:
          secretName: meu-segredo-banco
          # defaultMode: 0400 # Opcional: Define permissão do arquivo (apenas leitura para owner)