apiVersion: v1
kind: Secret
metadata:
  name: meu-segredo-banco
  namespace: default
type: Opaque
# stringData permite escrever texto plano no YAML. 
# O K8s converte para Base64 automaticamente ao salvar.
stringData:
  # --- DADO 1: Vai virar Variável de Ambiente ---
  senha-db: "minha-senha-super-secreta-123"

  # --- DADO 2: Vai virar um Arquivo físico ---
  id_rsa: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    MIIEogIBAAKCAQEArND... (conteudo falso de chave)
    Esta eh uma chave SSH privada simulada
    -----END OPENSSH PRIVATE KEY-----